# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
variables:
  github_token: $(GH_TOKEN)

jobs:
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'
  - script: |
      npm install -g yarn
      yarn
      yarn build
      npx cross-env GH_TOKEN=$(github_token) yarn build:x64 --win
      npx cross-env GH_TOKEN=$(github_token) yarn build:x86 --win
      npx cross-env GH_TOKEN=$(github_token) yarn upload
    displayName: 'windows install and build'
- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'
  - script: |
      npm install -g yarn
      yarn
      yarn build
      npx cross-env GH_TOKEN=$(github_token) yarn build:x64 --mac
      npx cross-env GH_TOKEN=$(github_token) yarn upload
    displayName: 'mac install and build'
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'
  - script: |
      npm install -g yarn
      yarn
      yarn build
      npx cross-env GH_TOKEN=$(github_token) yarn build:x64 --linux
      npx cross-env GH_TOKEN=$(github_token) yarn build:x86 --linux
      npx cross-env GH_TOKEN=$(github_token) yarn upload
    displayName: 'linux install and build'