# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master


jobs:
- job: Windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: CmdLine@2
    inputs:
      script: 'set GH_TOKEN=$(GH_TOKEN)'
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'
  - script: |
      npm install -g yarn
      yarn
      yarn build
      yarn build:x64 --win
      yarn build:x86 --win
      yarn upload -p always
    displayName: 'windows install and build'
- job: macOS
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - task: CmdLine@2
    inputs:
      script: 'export GH_TOKEN=$(GH_TOKEN)'
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'
  - script: |
      npm install -g yarn
      yarn
      yarn build
      yarn build:x64 --mac
      yarn upload -p always
    displayName: 'mac install and build'
- job: Linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: CmdLine@2
    inputs:
      script: 'export GH_TOKEN=$(GH_TOKEN)'
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'
  - script: |
      npm install -g yarn
      yarn
      yarn build
      yarn build:x64 --linux
      yarn build:x86 --linux
      yarn upload -p always
    displayName: 'linux install and build'